- name: Pre NVUE revision
  hosts: all
  connection: ansible.netcommon.httpapi
  gather_facts: false
  tasks:
    - name: Include NVUE revision pre
      include_role:
        name: nvue_revision
        tasks_from: pre

- name: Run config for NVUE-capable switches
  connection: ansible.netcommon.httpapi
  hosts: all
  gather_facts: false
  roles:
    - role: base_config          # Common setup (hostname, SNMP, etc)
    - role: nvue_config          # NVUE over HTTPAPI

- name: Post NVUE revision
  hosts: all
  connection: ansible.netcommon.httpapi
  gather_facts: false
  tasks:
    - name: Include NVUE revision post
      include_role:
        name: nvue_revision
        tasks_from: post
